apiVersion: v1
kind: Service
metadata:
  name: fastapi-todo-service
spec:
  type: NodePort  # Let's keep it accessible on the node
  selector:
    app: fastapi-todo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # You can change or remove this for random port